Indicio-tech/pydid

.github/workflows/code-quality-check.yml
.github/workflows/python-package.yml

feat: add github action

---

.github/workflows/code-quality-check.yml
pydid/__init__.py
pydid/doc/verification_method.py
pydid/doc/verification_relationship.py
requirements.dev.txt

Black code formatting and conventional commit checks.

More code checks

---

.flake8
pydid/doc/didcomm_service.py
pydid/doc/service.py
pydid/doc/verification_method.py
tests/doc/test_didcomm_service.py
tests/doc/test_service.py
tests/doc/test_verification_method.py

Including a base Service and a specialized DIDComm Service

Add service objects

---

poetry.lock
pydid/__init__.py
pydid/did.py
pydid/did_url.py
pydid/doc/__init__.py
pydid/doc/didcomm_service.py
pydid/doc/doc.py
pydid/doc/doc_options.py
pydid/doc/service.py
pydid/doc/verification_method.py
pydid/doc/verification_method_options.py
pydid/doc/verification_relationship.py
pydid/options.py
pydid/validation.py
pyproject.toml
tests/doc/test_didcomm_service.py
tests/doc/test_doc.py
tests/doc/test_doc_options.py
tests/doc/test_service.py
tests/doc/test_verification_method.py
tests/doc/test_verification_relationship.py
tests/int/scripts/get_uniresolver_examples.py
tests/int/test_docs.json
tests/int/test_uniresolver_docs.py
tests/int/uniresolver_config.json
tests/test_did.py
tests/test_did_url.py

Add DID Document class and associated helpers.

DID Document Object

---

.github/workflows/publish-release.yml

chore: add github workflow for publish release

---

.github/workflows/publish-release.yml

fix: use different poetry mechanism for publish

---

pyproject.toml

Prepare 0.2.0

---

pydid/doc/doc.py
pyproject.toml
setup.py

feat: add to_json method

---

pydid/doc/verification_method_options.py

fix: clobbering of controller value when using missing_controller option

---

pyproject.toml

Prepare 0.2.4 release

---

pyproject.toml

Prepare 0.2.5 release

---

pydid/doc/verification_method.py
tests/doc/test_doc.py
tests/doc/test_verification_method.py

fix: verification key not verification for ed25519

---

pydid/doc/builder.py
pydid/validation.py
pydid/verification_method.py
tests/doc/test_doc.py
tests/test_verification_method.py

feat: infer material based on known material properties

---

pydid/verification_method.py
pyproject.toml
tests/test_verification_method.py

And bump version for pre-release publish.

feat: verification method types can report type

---

.github/workflows/code-quality-check.yml
.github/workflows/publish-release.yml
.gitignore

feat: use local actions only, better dependency caching

---

.github/workflows/code-quality-check.yml
pydid/doc/builder.py
tests/doc/test_doc.py

test: add_didcomm without defaults

---

pydid/common.py
tests/test_did.py

feat: allow % char in DID

---

pydid/doc/doc.py
pydid/resource.py
tests/test_resource.py

This acts as a convenience method for casting Resources to the anticipated type

feat: add dereference_as

---

pyproject.toml

Prepare 0.3.2 Release

---

pydid/resource.py
tests/test_resource.py

fix: error on parsing failure with unions

---

pydid/doc/builder.py
pydid/service.py
tests/doc/test_doc.py
tests/test_service.py

fix: didcomm service accepts "accept"

---

pydid/verification_method.py
tests/test_verification_method.py

This PR adds the [Multikey](https://www.w3.org/TR/vc-data-integrity/#multikey) Verification Method.

feat: add multikey vm

---

pydid/verification_method.py
tests/test_verification_method.py

This PR adds the [Multikey](https://www.w3.org/TR/vc-data-integrity/#multikey) Verification Method.

feat(backport 0.3.x): add multikey vm

---

.github/dependabot.yml

Dependabot is your friend!
Let me know if I should change interval frequency, or set chron schedule for when it should run - so that it doesn't spam you :-)
Signed-off-by: ff137 <ff137@proton.me>

👷 Configure dependabot workflow
